# Generated by Django 4.2.14 on 2024-07-16 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('11', '11')], max_length=2)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('booking_timeslot', models.IntegerField(choices=[(0, datetime.time(12, 30)), (1, datetime.time(13, 0)), (2, datetime.time(13, 30)), (3, datetime.time(14, 0)), (4, datetime.time(14, 30)), (5, datetime.time(20, 0)), (6, datetime.time(20, 30)), (7, datetime.time(21, 0)), (8, datetime.time(21, 30))], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking_name', models.CharField(max_length=100)),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
