# Generated by Django 4.2.14 on 2024-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_booking_booking_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_timeslot',
            field=models.TimeField(choices=[(0, '12:30'), (1, '13:00'), (2, '13:30'), (3, '14:00'), (4, '14:30'), (5, '20:00'), (6, '20:30'), (7, '21:00'), (8, '21:30')], default=0),
        ),
    ]
