# Generated by Django 4.2.14 on 2024-07-17 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_booking_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_timeslot',
            field=models.TimeField(choices=[(0, datetime.time(11, 0)), (1, datetime.time(12, 0)), (2, datetime.time(13, 0)), (3, datetime.time(14, 0)), (4, datetime.time(15, 0)), (5, datetime.time(19, 0)), (6, datetime.time(20, 0)), (7, datetime.time(21, 0)), (8, datetime.time(22, 0))], default=0),
        ),
    ]
