# Generated by Django 4.2.14 on 2024-07-18 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booking_booking_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_timeslot',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(20, 0), '08:00 PM')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
    ]
