# Generated by Django 4.2.14 on 2024-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_booking_booking_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinksMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Beers on Tap'), (2, 'Bottled Beers'), (3, ' Whiskey'), (4, 'Our Signature Cocktails'), (5, 'Wines'), (6, 'Apertifs'), (7, 'Alcohol-free Drinks')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Appetizers'), (2, 'Main Course'), (3, 'Desserts')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='2', max_length=2),
        ),
    ]
