# Generated by Django 4.2.14 on 2024-07-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_drinksmenuitem_foodmenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinksmenuitem',
            name='category',
            field=models.IntegerField(choices=[(4, 'Beers on Tap'), (5, 'Bottled Beers'), (6, ' Whiskey'), (7, 'Our Signature Cocktails'), (8, 'Wines'), (9, 'Apertifs'), (10, 'Alcohol-free Drinks')]),
        ),
    ]
